#!/bin/bash
set -e

echo "🚀 Postiz Docker Container Starting..."

# Generate .env file from environment variables
echo "📝 Generating .env file from environment variables..."

cat > /app/.env << EOF
# Auto-generated from Docker environment variables
# Generated at: $(date)

# Core URLs
MAIN_URL=${MAIN_URL}
FRONTEND_URL=${FRONTEND_URL}
NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
BACKEND_INTERNAL_URL=${BACKEND_INTERNAL_URL}

# Security
JWT_SECRET=${JWT_SECRET}

# Database
DATABASE_URL=${DATABASE_URL}

# Redis
REDIS_URL=${REDIS_URL}

# Temporal
TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS}

# General Settings
IS_GENERAL=${IS_GENERAL}
DISABLE_REGISTRATION=${DISABLE_REGISTRATION}

# Storage
STORAGE_PROVIDER=${STORAGE_PROVIDER}
UPLOAD_DIRECTORY=${UPLOAD_DIRECTORY}
NEXT_PUBLIC_UPLOAD_DIRECTORY=${NEXT_PUBLIC_UPLOAD_DIRECTORY}

# Cloudflare R2 (Optional)
CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
CLOUDFLARE_ACCESS_KEY=${CLOUDFLARE_ACCESS_KEY}
CLOUDFLARE_SECRET_ACCESS_KEY=${CLOUDFLARE_SECRET_ACCESS_KEY}
CLOUDFLARE_BUCKETNAME=${CLOUDFLARE_BUCKETNAME}
CLOUDFLARE_BUCKET_URL=${CLOUDFLARE_BUCKET_URL}
CLOUDFLARE_REGION=${CLOUDFLARE_REGION}

# Social Media APIs
X_API_KEY=${X_API_KEY}
X_API_SECRET=${X_API_SECRET}
LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
BEEHIIVE_API_KEY=${BEEHIIVE_API_KEY}
BEEHIIVE_PUBLICATION_ID=${BEEHIIVE_PUBLICATION_ID}
THREADS_APP_ID=${THREADS_APP_ID}
THREADS_APP_SECRET=${THREADS_APP_SECRET}
FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
TIKTOK_CLIENT_ID=${TIKTOK_CLIENT_ID}
TIKTOK_CLIENT_SECRET=${TIKTOK_CLIENT_SECRET}
PINTEREST_CLIENT_ID=${PINTEREST_CLIENT_ID}
PINTEREST_CLIENT_SECRET=${PINTEREST_CLIENT_SECRET}
DRIBBBLE_CLIENT_ID=${DRIBBBLE_CLIENT_ID}
DRIBBBLE_CLIENT_SECRET=${DRIBBBLE_CLIENT_SECRET}
DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
DISCORD_BOT_TOKEN_ID=${DISCORD_BOT_TOKEN_ID}
SLACK_ID=${SLACK_ID}
SLACK_SECRET=${SLACK_SECRET}
SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
MASTODON_URL=${MASTODON_URL}
MASTODON_CLIENT_ID=${MASTODON_CLIENT_ID}
MASTODON_CLIENT_SECRET=${MASTODON_CLIENT_SECRET}

# OAuth Settings
NEXT_PUBLIC_POSTIZ_OAUTH_DISPLAY_NAME=${NEXT_PUBLIC_POSTIZ_OAUTH_DISPLAY_NAME}
NEXT_PUBLIC_POSTIZ_OAUTH_LOGO_URL=${NEXT_PUBLIC_POSTIZ_OAUTH_LOGO_URL}
POSTIZ_GENERIC_OAUTH=${POSTIZ_GENERIC_OAUTH}
POSTIZ_OAUTH_URL=${POSTIZ_OAUTH_URL}
POSTIZ_OAUTH_AUTH_URL=${POSTIZ_OAUTH_AUTH_URL}
POSTIZ_OAUTH_TOKEN_URL=${POSTIZ_OAUTH_TOKEN_URL}
POSTIZ_OAUTH_USERINFO_URL=${POSTIZ_OAUTH_USERINFO_URL}
POSTIZ_OAUTH_CLIENT_ID=${POSTIZ_OAUTH_CLIENT_ID}
POSTIZ_OAUTH_CLIENT_SECRET=${POSTIZ_OAUTH_CLIENT_SECRET}
POSTIZ_OAUTH_SCOPE=${POSTIZ_OAUTH_SCOPE}

# Sentry
NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
SENTRY_SPOTLIGHT=${SENTRY_SPOTLIGHT}
SENTRY_ORG=${SENTRY_ORG}
SENTRY_PROJECT=${SENTRY_PROJECT}
SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}

# Misc
OPENAI_API_KEY=${OPENAI_API_KEY}
NEXT_PUBLIC_DISCORD_SUPPORT=${NEXT_PUBLIC_DISCORD_SUPPORT}
NEXT_PUBLIC_POLOTNO=${NEXT_PUBLIC_POLOTNO}
API_LIMIT=${API_LIMIT}
NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION}

# Payments
FEE_AMOUNT=${FEE_AMOUNT}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_SIGNING_KEY=${STRIPE_SIGNING_KEY}
STRIPE_SIGNING_KEY_CONNECT=${STRIPE_SIGNING_KEY_CONNECT}

# Developer Settings
NX_ADD_PLUGINS=${NX_ADD_PLUGINS}

# Short Link Services
DUB_TOKEN=${DUB_TOKEN}
DUB_API_ENDPOINT=${DUB_API_ENDPOINT}
DUB_SHORT_LINK_DOMAIN=${DUB_SHORT_LINK_DOMAIN}
SHORT_IO_SECRET_KEY=${SHORT_IO_SECRET_KEY}
KUTT_API_KEY=${KUTT_API_KEY}
KUTT_API_ENDPOINT=${KUTT_API_ENDPOINT}
KUTT_SHORT_LINK_DOMAIN=${KUTT_SHORT_LINK_DOMAIN}
LINK_DRIP_API_KEY=${LINK_DRIP_API_KEY}
LINK_DRIP_API_ENDPOINT=${LINK_DRIP_API_ENDPOINT}
LINK_DRIP_SHORT_LINK_DOMAIN=${LINK_DRIP_SHORT_LINK_DOMAIN}
EOF

echo "✅ Environment file created at /app/.env"

# Ensure uploads directory exists with correct permissions
echo "📁 Setting up uploads directory..."
mkdir -p /uploads
chmod 755 /uploads
echo "✅ Uploads directory ready"

# Run database migrations
echo "🗄️  Running database migrations..."
pnpm run prisma-db-push || echo "⚠️  Database migration failed or already up to date"

# Start nginx
echo "🌐 Starting nginx..."
nginx

# Start applications with PM2
echo "🚀 Starting applications..."
cd /app
exec pnpm run pm2
